# Generated by Django 5.0.1 on 2026-01-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='completed',
            field=models.BooleanField(default=False, help_text='Mark as completed to lock the game from score manager edits'),
        ),
    ]
