# Generated by Django 5.0.1 on 2026-01-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_match_team_a_alter_match_team_b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledMessage',
        ),
    ]
