# Generated by Django 5.0.1 on 2026-02-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_team_unique_together_alter_team_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournament_round',
            field=models.PositiveIntegerField(blank=True, help_text='DEPRECATED - Use match_stage field instead', null=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['game', 'scheduled_at'], name='core_match_game_id_081a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='core_match_status_b71399_idx'),
        ),
    ]
